### PR TITLE
Truncate files Py way, save a syscall

### PR DESCRIPTION
**Pull request by zstyblik**
Commit replaces couple of os.system("echo '' > ...") with open('...', 'w') as it
will truncate file as well and we don't have to use a syscall for that.

### CODE REVIEW

**Comment by zstyblik** [comment]
btw personally, I use `cat /dev/null > /path/to/whatever.file` and I consider it to be cleaner, although I can't tell you why :)

**Comment by entropy1337** [comment]
Hello Zdenek, 
thank you for your patch and better line of code.  I accepted the patch.

**Comment by entropy1337** [comment]
dude, I also added a credit towards you on README where it is due. 
thank you

**Comment by zstyblik** [comment]
@entropy1337, thank you :)

**Pull request merged**
