### PR TITLE
Cleanup #3

### PR DESCRIPTION
**Pull request by zstyblik**
Remove the rest of `*.pyc` files and `wiki/index.html.bak`. This should be all for cleanup.

Once merged, https://github.com/entropy1337/infernal-twin/pull/10 can be closed, because it won't be necessary any more, resp. this PR covers issues in referenced PR.

### CODE REVIEW

**Comment by zstyblik** [comment]
Hm, files `importtry.py` and `try.py` could have been removed as well? What do you think @entropy1337?

**Comment by entropy1337** [comment]
you are right. 
I was playing around till i created the stable version. those are dummy files. I need a lot of cleaning to do on the folder. I think of putting all those files except the main execution on a separate folder.

**Comment by zstyblik** [comment]
Sure, no worries :) The biggest pain are `*.pyc` files, I'd say. Anyway, I've removed mentioned files and pushed the commit.

**Comment by entropy1337** [comment]
I accepted your pull requests and updated accordingly.
Thank you Zdenek for your time and help.

**Comment by zstyblik** [comment]
> I accepted your pull requests and updated accordingly.

Please, accept this PR too. It's consecutive to previous ones. Thank you.

> Thank you Zdenek for your time and help.

You're welcome :)

**Pull request merged**
