### PR TITLE
Extend and improve output of wireless scan

### PR DESCRIPTION
**Pull request by zstyblik**
Commit extends output of wireless scan with BSS(APs MAC address) information.
Also, case when SSID has a white space(and may be some non-ASCII chars as well)
in its name is being handled by this commit. As a result, parser of sorts of
% iw scan; output has been written.

### CODE REVIEW

**Comment by zstyblik** [comment]
I've added this, because I feel APs MAC address is somewhat useful, eg. to differentiate two APs with same SSID. It might be cool to have more detailed information(basically output from iwscan) upon a click or something. Or may be put output of iwscan into the right panel?

**Comment by entropy1337** [comment]
Hey dude, thank you for making improvement on the tool. 
I will merge it now. 
thanks.

**Comment by entropy1337** [comment]
Yes, you are right! 
Making more detailed output is good idea.

**Comment by entropy1337** [comment]
Hello Styblik, 
I have few ideas and features. I thought I could discuss with you over email. May I email you ? 3ntr0py1337@gmail.com

**Comment by zstyblik** [comment]
it's just a couple minutes a day. no biggie ;) I've sent you an email to that address.

**Comment by entropy1337** [comment]
Hello Zdenek,
Thanks for the email but I have not received the email yet. I will check
the spam or other folders.
Thanks.

**Pull request merged**
